### ISSUE TITLE
Empty result issue?

### ISSUE THREAD

**Issue by kanendosei** [lytics/multibayes#16]
Testing on Go 1.7 on OS X El Capitan 10.11.x, the included example returns an empty result of `Posterior Probabilities: map[]`

**Comment by allisonmorgan** [comment]
Whoops! I believe this has to do with [`minClassSize`](https://github.com/lytics/multibayes/blob/master/bayes.go#L9) being too high for the provided example. I will confirm this and update the example on the README.
