### ISSUE TITLE
Failing dependency: blevesearch's regexp tokenizer moved

### ISSUE THREAD

**Issue by numbleroot** [lytics/multibayes#18]
Hi!

When I try to build a project that depends on your multibayes package I get following error:
```
${GOPATH}/github.com/lytics/multibayes/tokenize.go:10:2: cannot find package "github.com/blevesearch/bleve/analysis/tokenizers/regexp_tokenizer" in any of: ...
```

I think, the package was moved on blevesearch's site. Could you update your code to reflect the changed dependency?

Thanks in advance.

**Comment by drewlanenga** [comment]
Thanks @numbleroot!

**Comment by numbleroot** [comment]
You're welcome! Thanks for the package :)
